# Generated by Django 4.0.3 on 2022-03-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('secondName', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=60)),
            ],
        ),
    ]
